name: 'Build'

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: { contents: write }

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew build

      - name: Short SHA
        id: vars
        run: echo "sha7=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Create nightly for commit
        if: startsWith(github.ref, 'refs/heads/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ci-${{ steps.vars.outputs.sha7 }}
          name: CI ${{ steps.vars.outputs.sha7 }}
          prerelease: true
          generate_release_notes: true
          files: |
            **/fabric/build/libs/*.jar
            **/neoforge/build/libs/*.jar
          fail_on_unmatched_files: true

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') && !startsWith(github.ref_name, 'ci-')
        with:
          files: |
            **/fabric/build/libs/*-${{ github.ref_name }}.jar
            **/neoforge/build/libs/*-${{ github.ref_name }}.jar
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true
